# Generated by Django 3.0.6 on 2020-05-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seagrassPercentage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='processedimage',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
